version: '3'
services:
  metric-server:
    container_name: metric-server
    image: metric-server:latest
    entrypoint: /metric-server
    environment:
      - COURIERS=7
      - LOG_LEVEL=DEBUG
      - PORT=12345
    networks:
    - testing_net

  test-client1:
    container_name: test-client1
    image: test-client:latest
    entrypoint: /test-client
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=metric-server:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOOP_PERIOD=5s
      - CLI_LOG_LEVEL=DEBUG
      - CLI_TYPE=METRIC
    networks:
      - testing_net
    depends_on:
      - metric-server

  test-client2:
    container_name: test-client2
    image: test-client:latest
    entrypoint: /test-client
    environment:
      - CLI_ID=2
      - CLI_SERVER_ADDRESS=metric-server:12345
      - CLI_LOOP_LAPSE=1m2s
      - CLI_LOOP_PERIOD=5s
      - CLI_LOG_LEVEL=DEBUG
      - CLI_TYPE=QUERY
    networks:
      - testing_net
    depends_on:
      - metric-server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24